package com.zallpy.openapproval.approval.listener.audit;

import com.zallpy.openapproval.approval.event.ApprovalStepTimedOutEvent;
import com.zallpy.openapproval.approval.service.audit.ApprovalAuditService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import org.springframework.transaction.event.TransactionPhase;
import org.springframework.transaction.event.TransactionalEventListener;

/**
 * Audit listener for {@link ApprovalStepTimedOutEvent}.
 *
 * <p>
 * Records an immutable audit entry whenever an
 * approval step exceeds its configured timeout
 * without receiving a decision.
 * </p>
 *
 * <p>
 * Timeout events are typically generated by the
 * approval timeout scheduler and may trigger
 * escalation, cancellation or automatic rejection,
 * depending on the configured approval policy.
 * </p>
 *
 * <p>
 * The listener executes only after the enclosing
 * transaction has successfully committed,
 * ensuring that audit history reflects only
 * committed business operations.
 * </p>
 *
 * <p>
 * Responsibilities:
 * <ul>
 * <li>Listen for {@link ApprovalStepTimedOutEvent}</li>
 * <li>Delegate audit recording to the audit service</li>
 * <li>Preserve a complete timeout history</li>
 * </ul>
 * </p>
 *
 * @author Zallpy
 * @since 1.0.0
 */
@Component
@RequiredArgsConstructor
public class ApprovalTimedOutAuditListener {

    /**
     * Approval audit service.
     */
    private final ApprovalAuditService approvalAuditService;

    /**
     * Handles approval step timeout events.
     *
     * <p>
     * The audit record is persisted only after
     * the surrounding transaction has been
     * successfully committed.
     * </p>
     *
     * @param event approval step timed out event
     */
    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onApprovalStepTimedOut(
            final ApprovalStepTimedOutEvent event) {

        approvalAuditService.record(event);
    }

}