package com.zallpy.openapproval.approval.listener.audit;

import com.zallpy.openapproval.approval.event.ApprovalReminderSentEvent;
import com.zallpy.openapproval.approval.service.audit.ApprovalAuditService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import org.springframework.transaction.event.TransactionPhase;
import org.springframework.transaction.event.TransactionalEventListener;

/**
 * Audit listener for {@link ApprovalReminderSentEvent}.
 *
 * <p>
 * Records an immutable audit entry whenever an
 * approval reminder is successfully sent to an
 * approver.
 * </p>
 *
 * <p>
 * Reminder events are typically generated by the
 * scheduler before an approval step reaches its
 * configured timeout.
 * </p>
 *
 * <p>
 * The listener executes only after the enclosing
 * transaction has successfully committed,
 * ensuring that the audit trail reflects
 * committed business operations.
 * </p>
 *
 * <p>
 * Responsibilities:
 * <ul>
 * <li>Listen for {@link ApprovalReminderSentEvent}</li>
 * <li>Delegate audit recording to the audit service</li>
 * <li>Preserve an immutable reminder history</li>
 * </ul>
 * </p>
 *
 * @author Zallpy
 * @since 1.0.0
 */
@Component
@RequiredArgsConstructor
public class ApprovalReminderSentAuditListener {

    /**
     * Approval audit service.
     */
    private final ApprovalAuditService approvalAuditService;

    /**
     * Handles approval reminder sent events.
     *
     * <p>
     * Records the reminder only after the
     * surrounding transaction has committed
     * successfully.
     * </p>
     *
     * @param event approval reminder sent event
     */
    @TransactionalEventListener(phase = TransactionPhase.AFTER_COMMIT)
    public void onApprovalReminderSent(
            final ApprovalReminderSentEvent event) {

        approvalAuditService.record(event);
    }

}